# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-15 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20180214_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='groups.Group'),
        ),
    ]
